kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-configmap

data:
  proxy.conf : |
    server {
      listen 80;
      server_name malikiah.io cloud.malikiah.io ;
      
      location / {
        proxy_pass http://proxy-ingress/;
      }
    }