{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nextcloud.serviceAccountName" . }}
  labels:
{{ include "nextcloud.labels" . | indent 4 }}
{{- end -}}
