apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nextcloud-mariadb-config-pvc

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi